In [9]:
import requests
import pandas as pd

In [10]:
from pprint import pprint

api_key = "31454b4282bc69567483ad1dd8d07af2"
city = "Kathmandu"
url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

response = requests.get(url)
if response.status_code == 200:
    data = response.json()
    pprint(data)
else:
    print("Status Code :", response.status_code)

{'base': 'stations',
 'clouds': {'all': 75},
 'cod': 200,
 'coord': {'lat': 27.7167, 'lon': 85.3167},
 'dt': 1769496368,
 'id': 1283240,
 'main': {'feels_like': 18.05,
          'grnd_level': 855,
          'humidity': 37,
          'pressure': 1017,
          'sea_level': 1017,
          'temp': 19.12,
          'temp_max': 19.12,
          'temp_min': 19.12},
 'name': 'Kathmandu',
 'sys': {'country': 'NP',
         'id': 9201,
         'sunrise': 1769476071,
         'sunset': 1769514882,
         'type': 1},
 'timezone': 20700,
 'visibility': 6000,
 'weather': [{'description': 'broken clouds',
              'icon': '04d',
              'id': 803,
              'main': 'Clouds'}],
 'wind': {'deg': 0, 'speed': 1.03}}

In [11]:
import pandas as pd
from pandas import json_normalize

df = json_normalize(data)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   weather          1 non-null      object
 1   base             1 non-null      object
 2   visibility       1 non-null      int64
 3   dt               1 non-null      int64
 4   timezone         1 non-null      int64
 5   id               1 non-null      int64
 6   name             1 non-null      object
 7   cod              1 non-null      int64
 8   coord.lon        1 non-null      float64
 9   coord.lat        1 non-null      float64
 10  main.temp        1 non-null      float64
 11  main.feels_like  1 non-null      float64
 12  main.temp_min    1 non-null      float64
 13  main.temp_max    1 non-null      float64
 14  main.pressure    1 non-null      int64
 15  main.humidity    1 non-null      int64
 16  main.sea_level   1 non-null      int64
 17  main.grnd_level  1 non-null      int64
 18  wind.speed       1 non-null      float64
 19  wind.deg         1 non-null      int64
 20  clouds.all       1 non-null      int64
 21  sys.type         1 non-null      int64
 22  sys.id           1 non-null      int64
 23  sys.country      1 non-null      object
 24  sys.sunrise      1 non-null      int64
 25  sys.sunset       1 non-null      int64
dtypes: float64(7), int64(15), object(4)
memory usage: 340.0+ bytes
None

In [12]:
df_weather = df[['name', 'main.temp', 'main.humidity', 'wind.speed', 'weather']]

df_weather.head()

,name,main.temp,main.humidity,wind.speed,weather
0,Kathmandu,19.12,37,1.03,"[{'id': 803, 'main': 'Clouds', 'description': ..."

In [13]:
df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])
df_weather = df_weather.drop(columns=['weather'])
df_weather

C:\Users\ACER\AppData\Local\Temp\ipykernel_11292\1660596148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])

        name  main.temp  main.humidity  wind.speed    description
0  Kathmandu      19.12             37        1.03  broken clouds

In [14]:
cities = ["Kathmandu", "Birtamode", "Dharan", "Biratnagar", "Pokhara"]
final_list = []
for city in cities:
    response = requests.get(f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&unit=metric")
    if response.status_code ==  200:
        data = response.json()
        print(data)
    else:
        print("Status code: ", response.status_code)
    df = json_normalize(data)
    df_weather = df[['name', 'main.temp', 'main.humidity', 'wind.speed', 'weather']]
    df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])
    df_weather = df_weather.drop(columns=['weather'])
    final_list.append(df_weather)

{'coord': {'lon': 85.3167, 'lat': 27.7167}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 292.27, 'feels_like': 291.2, 'temp_min': 292.27, 'temp_max': 292.27, 'pressure': 1017, 'humidity': 37, 'sea_level': 1017, 'grnd_level': 855}, 'visibility': 6000, 'wind': {'speed': 1.03, 'deg': 0}, 'clouds': {'all': 75}, 'dt': 1769496683, 'sys': {'type': 1, 'id': 9201, 'country': 'NP', 'sunrise': 1769476071, 'sunset': 1769514882}, 'timezone': 20700, 'id': 1283240, 'name': 'Kathmandu', 'cod': 200}
Status code:  404

C:\Users\ACER\AppData\Local\Temp\ipykernel_11292\4086241141.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])
C:\Users\ACER\AppData\Local\Temp\ipykernel_11292\4086241141.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])

{'coord': {'lon': 87.2835, 'lat': 26.8125}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 296.71, 'feels_like': 296.22, 'temp_min': 296.71, 'temp_max': 296.71, 'pressure': 1018, 'humidity': 42, 'sea_level': 1018, 'grnd_level': 970}, 'visibility': 10000, 'wind': {'speed': 2.74, 'deg': 199, 'gust': 2}, 'clouds': {'all': 65}, 'dt': 1769496805, 'sys': {'country': 'NP', 'sunrise': 1769475508, 'sunset': 1769514501}, 'timezone': 20700, 'id': 1283460, 'name': 'Dharān', 'cod': 200}
{'coord': {'lon': 87.2834, 'lat': 26.4831}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 298.46, 'feels_like': 297.96, 'temp_min': 298.46, 'temp_max': 298.46, 'pressure': 1017, 'humidity': 35, 'sea_level': 1017, 'grnd_level': 1008}, 'visibility': 10000, 'wind': {'speed': 1.39, 'deg': 185, 'gust': 1.53}, 'clouds': {'all': 51}, 'dt': 1769496892, 'sys': {'country': 'NP', 'sunrise': 1769475475, 'sunset': 1769514534}, 'timezone': 20700, 'id': 1283582, 'name': 'Biratnagar', 'cod': 200}

C:\Users\ACER\AppData\Local\Temp\ipykernel_11292\4086241141.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])
C:\Users\ACER\AppData\Local\Temp\ipykernel_11292\4086241141.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])

{'coord': {'lon': 83.9833, 'lat': 28.2333}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 294.68, 'feels_like': 293.59, 'temp_min': 294.68, 'temp_max': 294.68, 'pressure': 1018, 'humidity': 27, 'sea_level': 1018, 'grnd_level': 876}, 'visibility': 10000, 'wind': {'speed': 3.05, 'deg': 162, 'gust': 1.87}, 'clouds': {'all': 3}, 'dt': 1769496900, 'sys': {'country': 'NP', 'sunrise': 1769476443, 'sunset': 1769515149}, 'timezone': 20700, 'id': 1282898, 'name': 'Pokhara', 'cod': 200}

C:\Users\ACER\AppData\Local\Temp\ipykernel_11292\4086241141.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather['description'] = df_weather['weather'].apply(lambda x: x[0]['description'])

In [15]:
final_list

[        name  main.temp  main.humidity  wind.speed    description
 0  Kathmandu     292.27             37        1.03  broken clouds,
         name  main.temp  main.humidity  wind.speed    description
 0  Kathmandu     292.27             37        1.03  broken clouds,
      name  main.temp  main.humidity  wind.speed    description
 0  Dharān     296.71             42        2.74  broken clouds,
          name  main.temp  main.humidity  wind.speed    description
 0  Biratnagar     298.46             35        1.39  broken clouds,
       name  main.temp  main.humidity  wind.speed description
 0  Pokhara     294.68             27        3.05   clear sky]

In [16]:
dataframe = pd.concat(final_list, ignore_index=True)

In [17]:
dataframe

         name  main.temp  main.humidity  wind.speed    description
0   Kathmandu     292.27             37        1.03  broken clouds
1   Kathmandu     292.27             37        1.03  broken clouds
2      Dharān     296.71             42        2.74  broken clouds
3  Biratnagar     298.46             35        1.39  broken clouds
4     Pokhara     294.68             27        3.05      clear sky

In [18]:
dataframe.to_csv("Weather.csv", index=False)